# Generated by Django 4.2.16 on 2024-10-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre del autor')),
                ('biografia', models.TextField(max_length=100, verbose_name='biografia')),
                ('fnacimiento', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='nacionalidad')),
                ('estado', models.IntegerField(max_length=100, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_editorial', models.CharField(max_length=100, verbose_name='nombre de la Editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_idioma', models.CharField(max_length=100, verbose_name='nombre de idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=100, verbose_name='nombre del rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('correo', models.CharField(max_length=100, verbose_name='correo')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='fecha de creacion')),
                ('updated', models.DateTimeField(verbose_name='fecha de actualizacion')),
                ('estado', models.IntegerField(verbose_name='estado')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibiblioteca.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo de libro')),
                ('fpublicacion', models.DateField(verbose_name='fecha de publicacion')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('nro_paginas', models.IntegerField(verbose_name='numero de paginas')),
                ('estado', models.IntegerField(verbose_name='estado')),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibiblioteca.autor', verbose_name='id autor')),
                ('id_editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibiblioteca.editorial', verbose_name='id editorial')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibiblioteca.idioma')),
            ],
        ),
    ]
