# Generated by Django 4.2.16 on 2024-10-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mibiblioteca', '0002_alter_autor_estado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='Autor',
        ),
        migrations.AlterModelTable(
            name='editorial',
            table='Editorial',
        ),
        migrations.AlterModelTable(
            name='idioma',
            table='Idioma',
        ),
        migrations.AlterModelTable(
            name='libros',
            table='Libro',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='Rol',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='Usuario',
        ),
    ]
